version: "3"
services:
  apache-proxy:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend-server

  backend-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
